[package]
name = "minios-guest"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
build = "build.rs"

[dependencies]
minios-abi = { path = "../abi" }

[[bin]]
name = "minios-guest"
path = "src/main.rs"
test = false
bench = false
doctest = false

[[bin]]
name = "minios-guest-stdin-cat"
path = "src/bin/stdin_cat.rs"
test = false
bench = false
doctest = false

[[bin]]
name = "minios-guest-file-read"
path = "src/bin/file_read.rs"
test = false
bench = false
doctest = false

[[bin]]
name = "minios-guest-file-fd"
path = "src/bin/file_fd.rs"
test = false
bench = false
doctest = false

[[bin]]
name = "minios-guest-file-write"
path = "src/bin/file_write.rs"
test = false
bench = false
doctest = false

[[bin]]
name = "minios-guest-sched-a"
path = "src/bin/sched_a.rs"
test = false
bench = false
doctest = false

[[bin]]
name = "minios-guest-sched-b"
path = "src/bin/sched_b.rs"
test = false
bench = false
doctest = false

[[bin]]
name = "minios-guest-sched-r"
path = "src/bin/sched_r.rs"
test = false
bench = false
doctest = false
